<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUZ16CiP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUZ16CiP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUZ16CiP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUZ16CiP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUZ16CiP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UZ16CiP',
    'container.build_id' => '91b3438f',
    'container.build_time' => 1668420808,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUZ16CiP');
